name: Build and Publish to Docker Hub
permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mryoso17/portfolio:latest
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "mryoso17"
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the Docker image
        run: docker push mryoso17/portfolio:latest
